import { Inter } from 'next/font/google';
import './globals.css';

const interSans = Inter({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${interSans.variable} antialiased`}>
        <main className='max-w-7xl mx-auto w-full px-4 md:px-6 lg:px-8'>
          {children}
        </main>
      </body>
    </html>
  );
}
